services:
  postgres:
    image: postgres:18-alpine
    container_name: workout-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: workoutboard
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
  
  pgweb:
    image: sosedoff/pgweb
    container_name: workout-pgweb
    environment:
      DATABASE_URL: postgres://postgres:postgres@postgres:5432/workoutboard?sslmode=disable
    ports:
      - "8081:8081"
    depends_on:
      - postgres

volumes:
  postgres-data: